---

- name: Copy profile to /etc/profile.d/
  ansible.builtin.copy:
    src: profile.d/
    dest: /etc/profile.d/
    owner: root
    group: root
    mode: "0755"
  notify:
    - Load-profile

- name: Copy sysctl to /etc/sysctl.d/
  ansible.builtin.copy:
    src: sysctl.d/
    dest: /etc/sysctl.d/
    owner: root
    group: root
    mode: "0644"
  notify:
    - Load-sysctl

- name: Copy sshd_config to /etc/ssh/sshd_config.d/
  ansible.builtin.copy:
    src: sshd_config.d/
    dest: /etc/ssh/sshd_config.d/
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart-sshd

- name: Copy journald to /etc/systemd/journald.conf.d
  ansible.builtin.copy:
    src: journald.conf.d/
    dest: /etc/systemd/journald.conf.d/
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart-journald

- name: Copy apt to /etc/apt/apt.conf.d/
  ansible.builtin.copy:
    src: apt.conf.d/
    dest: /etc/apt/apt.conf.d/
    owner: root
    group: root
    mode: "0644"

- name: Copy fail2ban jail to /etc/fail2ban/jail.d/
  ansible.builtin.copy:
    src: jail.d/
    dest: /etc/fail2ban/jail.d/
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart-fail2ban

- name: Copy fail2ban filter to /etc/fail2ban/filter.d/
  ansible.builtin.copy:
    src: filter.d/
    dest: /etc/fail2ban/filter.d/
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart-fail2ban
