---
- name: Prepare for installation
  ansible.builtin.include_tasks: prepare.yml

- name: Copy default configuration
  ansible.builtin.include_tasks: configuration.yml

- name: Set limits
  ansible.builtin.include_tasks: limits.yml

- name: Set timezone
  ansible.builtin.include_tasks: timezone.yml

- name: Set locale
  ansible.builtin.include_tasks: locale.yml

- name: Set motd
  ansible.builtin.include_tasks: motd.yml

- name: Set otpauth
  ansible.builtin.include_tasks: otpauth.yml
