---

- name: Distribute motd file for debian
  ansible.builtin.template:
    src: debian-motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: "0644"
  when: ansible_os_family == "Debian"
