---

- name: APT | Remove packages that are left over dependencies (no longer needed)
  ansible.builtin.apt:
    autoremove: true
  when: debian_apt_autoremove
  register: apt_autoremove_var
  changed_when: "'Removed' in apt_autoremove_var.stdout"

- name: APT | Clear local repository of retrieved package files
  ansible.builtin.apt:
    autoclean: true
  when: debian_apt_autoclean
  register: apt_autoclean_var
  changed_when: "'Deleted' in apt_autoclean_var.stdout"

- name: APT | Update the apt cache
  ansible.builtin.apt:
    update_cache: true

- name: APT | Make sure the default packages are installed
  ansible.builtin.apt:
    pkg: "{{ debian_apt_default_packages | join(',') }}"
    state: present
