---

- name: Distribute sshd file for debian
  ansible.builtin.template:
    src: 99-sshd_config.conf.j2
    dest: /etc/ssh/sshd_config.d/99-sshd_config.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart-sshd
