---

- name: Set logging
  community.general.ufw:
    logging: 'on'

- name: Deny everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: deny

- name: Allow port {{ debian_openssh_port }}
  community.general.ufw:
    rule: allow
    port: '{{ debian_openssh_port }}'
    proto: tcp
