---

- name: Restart-sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    enabled: true

- name: Restart-journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
    enabled: true

- name: Restart-fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    enabled: true

- name: Load-profile
  ansible.builtin.command:
    cmd: bash -c 'source /etc/profile.d/umask.sh'
  changed_when: false
  become: true

- name: Load-sysctl
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.d/99-sysctl.conf
  changed_when: false
  become: true
