---

- name: Create user group
  ansible.builtin.group:
    name: "{{ group }}"

- name: Create user account
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ 'password' | password_hash('sha512') }}"
    update_password: on_create
    shell: /bin/bash
    group: "{{ group }}"
    groups:
      - sudo
    append: true

- name: Add public key to "{{ username }}"
  ansible.posix.authorized_key:
    exclusive: true
    key: "{{ lookup('file', 'id_ed25519.pub') }}"
    user: "{{ username }}"
    state: present
