---

debian_openssh_port: 60022
debian_apt_cache_valid_time: 3600
debian_apt_autoremove: true
debian_apt_autoclean: true
debian_apt_config:
  "APT::Install-Recommends": "no"
  "APT::Install-Suggests": "no"
  "APT::Get::Show-Upgraded": "yes"

debian_apt_default_packages:
  - sudo
  - vim
  - rsync
  - apt-transport-https
  - ca-certificates
  - wget
  - net-tools
  - lsb-release
  - software-properties-common
  - gnupg2
  - curl
  - lrzsz
  - git
  - jq
  - bash-completion
  - command-not-found
  - fail2ban
  - psmisc
  - htop
  - ufw

debian_timezone: Asia/Shanghai

debian_locale: en_US.UTF-8

debian_limits_conf_settings:
  - domain: "*"
    limit_type: soft
    limit_item: nofile
    value: 655350

  - domain: "*"
    limit_type: hard
    limit_item: nofile
    value: 655350

  - domain: "*"
    limit_type: soft
    limit_item: nproc
    value: 131072

  - domain: "*"
    limit_type: hard
    limit_item: nproc
    value: 131072

  - domain: "*"
    limit_type: soft
    limit_item: core
    value: 0

  - domain: "*"
    limit_type: hard
    limit_item: core
    value: 0
